### PR TITLE
Fix build with rizin 0.7.0

### LINKED ISSUE #25: rz-plugin/data.cpp:167:64: error: ‘RzListIter’ {aka ‘struct rz_list_iter_t’} has no member named ‘n’
```
/home/runner/work/rz-retdec/rz-retdec/src/rz-plugin/data.cpp: In member function ‘void retdec::rzplugin::RizinDatabase::fetchFunctionsAndGlobals(retdec::config::Config&) const’:
/home/runner/work/rz-retdec/rz-retdec/src/rz-plugin/data.cpp:167:64: error: ‘RzListIter’ {aka ‘struct rz_list_iter_t’} has no member named ‘n’
  167 |                 for (RzListIter *it = list->head; it; it = it->n) {
      |                                                                ^
/home/runner/work/rz-retdec/rz-retdec/src/rz-plugin/data.cpp:168:78: error: ‘RzListIter’ {aka ‘struct rz_list_iter_t’} has no member named ‘data’
  168 |                         auto fnc = reinterpret_cast<RzAnalysisFunction*>(it->data);
      |                                                                              ^~~~
/home/runner/work/rz-retdec/rz-retdec/src/rz-plugin/data.cpp: In member function ‘void retdec::rzplugin::RizinDatabase::fetchGlobals(retdec::config::Config&) const’:
/home/runner/work/rz-retdec/rz-retdec/src/rz-plugin/data.cpp:209:37: error: ‘struct rz_pvector_t’ has no member named ‘head’
  209 |         for (RzListIter *it = list->head; it; it = it->n) {
      |                                     ^~~~
/home/runner/work/rz-retdec/rz-retdec/src/rz-plugin/data.cpp:209:56: error: ‘RzListIter’ {aka ‘struct rz_list_iter_t’} has no member named ‘n’
  209 |         for (RzListIter *it = list->head; it; it = it->n) {
      |                                                        ^
/home/runner/work/rz-retdec/rz-retdec/src/rz-plugin/data.cpp:210:63: error: ‘RzListIter’ {aka ‘struct rz_list_iter_t’} has no member named ‘data’
  210 |                 auto sym = reinterpret_cast<RzBinSymbol*>(it->data);
      |                                                               ^~~~
/home/runner/work/rz-retdec/rz-retdec/src/rz-plugin/data.cpp: In member function ‘void retdec::rzplugin::RizinDatabase::fetchExtraArgsData(retdec::common::ObjectSequentialContainer&, RzAnalysisFunction&) const’:
/home/runner/work/rz-retdec/rz-retdec/src/rz-plugin/data.cpp:366:64: error: ‘RzListIter’ {aka ‘struct rz_list_iter_t’} has no member named ‘n’
  366 |                 for (RzListIter *it = list->head; it; it = it->n) {
      |                                                                ^
/home/runner/work/rz-retdec/rz-retdec/src/rz-plugin/data.cpp:367:72: error: ‘RzListIter’ {aka ‘struct rz_list_iter_t’} has no member named ‘data’
  367 |                         arg = reinterpret_cast<RzAnalysisFuncArg*>(it->data);
      |                                                                        ^~~~
```

### LINKED ISSUE #27: Fetch global variables normally from Rizin
Currently there is an ugly hack in `src/rz-plugin/data.cpp` - `fetchGlobals()` function.

Since Rizin supports global variables for a while already, just use the corresponding APIs (see e.g. how `afg` is implemented).
See `rz_analysis_var_global_*()` APIs

To fetch all those, `rz_analysis_var_global_get_all()` could be used

### PR DESCRIPTION
**Pull request by XVilka**
Closes https://github.com/rizinorg/rz-retdec/issues/25
Closes https://github.com/rizinorg/rz-retdec/issues/27

### CODE REVIEW

**Comment by XVilka** [comment]
It builds and runs fine now, the only red thing is the failing test: https://github.com/rizinorg/rz-retdec/issues/19
